### PR TITLE
Support for GNOME 40

### PR DESCRIPTION
**Pull request by arushsharma24**
As per the comments on the Extension website on gnome.org by DonnyBravo and sidethorn. Tested on my Gnome 40.5 system on Arch, and seems to work fine. This will, however, make it incompatible with Gnome 3 versions, so I am not sure whether this should be merged in this repository or else it could be launched as a separate extension.

I don't know how to make this extension work differently for different versions of GNOME, so if someone could help me with that, that would also be great, and we could do that.

### CODE REVIEW

**Comment by squgeim** [comment]
Thanks for the contribution. I haven't really been using Gnome day to day so the extension had fallen behind, thank you for bringing it up to date. I will test the changes on my end then merge and release it. It'll be just a few days.

**Comment by arushsharma24** [comment]
Hey, just a reminder incase you forgot.

**Comment by squgeim** [comment]
Thanks for the reminder! You are right, this fell through the cracks and I
totally forgot. :D I am on it tonight.

**Comment by squgeim** [comment]
The changes look good. Although I had to bump the version to make it work in the latest Fedora (gnome 41).

**Pull request merged**
